(defpackage :glop2/ffi-win32
  (:use #:cl #:cffi)
  (:export
   #:handle
   #:hdc
   #:hwnd
   #:bool
   #:get-module-handle
   #:adjust-window-rect-ex
   #:create-and-register-class
   #:create-window-ex
   #:get-last-error-string
   #:client-to-screen
   #:get-client-rect
   #:get-dc
   #:get-version
   #:set-foreground-window
   #:show-window
   #:update-window
   #:%release-dc
   #:release-dc
   #:set-geometry
   #:set-focus
   #:set-window-text
   #:show-cursor
   #:%event%
   #:msg
   #:%get-message
   #:%translate-message
   #:%peek-message
   #:%dispatch-message
   #:with-message
   #:wparam
   #:lparam
   #:%post-quit-message
   #:low-word
   #:high-word
   #:win32-lookup-key
   #:set-capture
   #:release-capture
   #:%def-window-proc
   #:get-physical-cursor-pos
   #:get-cursor-pos
   #:set-physical-cursor-pos
   #:load-cursor
   #:set-cursor
   #:destroy-cursor
   #:enum-display-monitors
   #:bring-window-to-top
   #:set-window-pos
   #:+hwnd-no-topmost+
   #:+hwnd-topmost+
   #:+hwnd-top+
   #:+hwnd-bottom+
   #:get-system-metrics
   #:get-dc-ex
   #:hbitmap
   #:get-update-rect
   #:word
   #:dword
   #:long
   #:dwordlong
   #:boolean
   #:dword32
   #:longlong
   #:long64))
